/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clases;

import javax.swing.JOptionPane;

/**
 *
 * @author jefe
 */
public class DatosPersonalesAlexisEncalada extends javax.swing.JFrame {

    /**
     * Creates new form DatosPersonalesAlexisEncalada
     */
    public DatosPersonalesAlexisEncalada() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblTitulo = new javax.swing.JLabel();
        lblCed = new javax.swing.JLabel();
        lblPro = new javax.swing.JLabel();
        lblPla = new javax.swing.JLabel();
        lblAño = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblCol = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblVal = new javax.swing.JLabel();
        Lblmul = new javax.swing.JLabel();
        txtCedu = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtPlaca = new javax.swing.JTextField();
        txtAño = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        txtTipo = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        txtMultas = new javax.swing.JTextField();
        ButtnValidar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LblTitulo.setForeground(new java.awt.Color(255, 0, 0));
        LblTitulo.setText("DATOS DE VEHICULO A MATRICULAR");

        lblCed.setForeground(new java.awt.Color(0, 0, 255));
        lblCed.setText("Número de Cédula del Propietario ");

        lblPro.setForeground(new java.awt.Color(0, 51, 204));
        lblPro.setText("Nombre del Propietario ");

        lblPla.setForeground(new java.awt.Color(0, 51, 204));
        lblPla.setText("Número de placa ");

        lblAño.setForeground(new java.awt.Color(0, 51, 204));
        lblAño.setText("Año de Fabricación del Vehículo ");

        lblMarca.setForeground(new java.awt.Color(0, 51, 153));
        lblMarca.setText("Marca ");

        lblCol.setForeground(new java.awt.Color(0, 51, 153));
        lblCol.setText("Color ");

        lblTipo.setForeground(new java.awt.Color(0, 51, 153));
        lblTipo.setText("Tipo de Vehículo ");

        lblVal.setForeground(new java.awt.Color(0, 51, 153));
        lblVal.setText("Valor del Vehículo ");

        Lblmul.setForeground(new java.awt.Color(0, 51, 153));
        Lblmul.setText("Posee o no multas ");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        ButtnValidar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ButtnValidar.setForeground(new java.awt.Color(255, 0, 0));
        ButtnValidar.setText("VALIDAR DATOS");
        ButtnValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtnValidarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblCed)
                        .addComponent(lblPro, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblPla, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblAño, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblMarca, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblCol, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblTipo, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(lblVal)
                    .addComponent(Lblmul))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtCedu, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtPlaca, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtAño, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtMarca)
                        .addComponent(txtColor)
                        .addComponent(txtTipo, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE))
                    .addComponent(txtMultas, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(LblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(ButtnValidar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LblTitulo)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCed)
                    .addComponent(txtCedu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPro))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPla))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAño)
                    .addComponent(txtAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMarca)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCol)
                    .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipo)
                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lblmul)
                    .addComponent(txtMultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(ButtnValidar)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void ButtnValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtnValidarActionPerformed
        // TODO add your handling code here:
                                             
    String Cedula = txtCedu.getText();
    String Nombre = txtNombre.getText();
    String Placa = txtPlaca.getText();
    String Fabricacion = txtAño.getText();
    String Marca = txtMarca.getText();
    String Color = txtColor.getText();
    String Tipo = txtTipo.getText();
    String Valor = txtValor.getText();
    String Multa = txtMultas.getText();

    // Construir el mensaje con todos los datos
    StringBuilder mensaje = new StringBuilder("Datos ingresados:\n");
    mensaje.append("Cedula: ").append(Cedula).append("\n");
    mensaje.append("Nombre: ").append(Nombre).append("\n");
    mensaje.append("Placa: ").append(Placa).append("\n");
    mensaje.append("Año de Fabricación: ").append(Fabricacion).append("\n");
    mensaje.append("Marca: ").append(Marca).append("\n");
    mensaje.append("Color: ").append(Color).append("\n");
    mensaje.append("Tipo: ").append(Tipo).append("\n");
    mensaje.append("Valor: ").append(Valor).append("\n");
    mensaje.append("Multa: ").append(Multa).append("\n");

    // Mostrar el JOptionPane con todos los datos
    JOptionPane.showMessageDialog(this, mensaje.toString(), "Datos Ingresados", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_ButtnValidarActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatosPersonalesAlexisEncalada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatosPersonalesAlexisEncalada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatosPersonalesAlexisEncalada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatosPersonalesAlexisEncalada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatosPersonalesAlexisEncalada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtnValidar;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JLabel Lblmul;
    private javax.swing.JLabel lblAño;
    private javax.swing.JLabel lblCed;
    private javax.swing.JLabel lblCol;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblPla;
    private javax.swing.JLabel lblPro;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblVal;
    private javax.swing.JTextField txtAño;
    private javax.swing.JTextField txtCedu;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtMultas;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtTipo;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
