/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clases;

import javax.swing.JOptionPane;

/**
 *
 * @author jefe
 */
public class FichaAlexisEncalada extends javax.swing.JFrame {

    /**
     * Creates new form FichaAlexisEncalada
     */
    public FichaAlexisEncalada() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMarca = new javax.swing.JLabel();
        txtColor = new javax.swing.JTextField();
        lblCol = new javax.swing.JLabel();
        txtTipo = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        lblTipo = new javax.swing.JLabel();
        lblVal = new javax.swing.JLabel();
        ButtnValidar = new javax.swing.JButton();
        txtCedu = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtPlaca = new javax.swing.JTextField();
        LblTitulo = new javax.swing.JLabel();
        lblCed = new javax.swing.JLabel();
        lblPro = new javax.swing.JLabel();
        lblPla = new javax.swing.JLabel();
        txtAño = new javax.swing.JTextField();
        lblAño = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMarca.setForeground(new java.awt.Color(0, 51, 153));
        lblMarca.setText("Marca ");

        lblCol.setForeground(new java.awt.Color(0, 51, 153));
        lblCol.setText("Color ");

        lblTipo.setForeground(new java.awt.Color(0, 51, 153));
        lblTipo.setText("Tipo de Vehículo ");

        lblVal.setForeground(new java.awt.Color(0, 51, 153));
        lblVal.setText("Valor del Vehículo ");

        ButtnValidar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ButtnValidar.setForeground(new java.awt.Color(255, 0, 0));
        ButtnValidar.setText("VALIDAR DATOS");
        ButtnValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtnValidarActionPerformed(evt);
            }
        });

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        LblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LblTitulo.setForeground(new java.awt.Color(255, 0, 0));
        LblTitulo.setText("DATOS DE VEHICULO A MATRICULAR");

        lblCed.setForeground(new java.awt.Color(0, 0, 255));
        lblCed.setText("Número de Cédula del Propietario ");

        lblPro.setForeground(new java.awt.Color(0, 51, 204));
        lblPro.setText("Nombre del Propietario ");

        lblPla.setForeground(new java.awt.Color(0, 51, 204));
        lblPla.setText("Número de placa ");

        lblAño.setForeground(new java.awt.Color(0, 51, 204));
        lblAño.setText("Año de Fabricación del Vehículo ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblCed)
                        .addComponent(lblPro, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblPla, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblAño, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblMarca, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblCol, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblTipo, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(lblVal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtCedu, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtPlaca, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtAño, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtMarca)
                        .addComponent(txtColor)
                        .addComponent(txtTipo, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(LblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(ButtnValidar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LblTitulo)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCed)
                    .addComponent(txtCedu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPro))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPla))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAño)
                    .addComponent(txtAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMarca)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCol)
                    .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipo)
                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(54, 54, 54)
                .addComponent(ButtnValidar)
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtnValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtnValidarActionPerformed
        // TODO add your handling code here:
        String Cedula= txtCedu.getText();
        String Nombre= txtNombre.getText();
        String Placa = txtPlaca.getText();
        String Fabricacion= txtAño.getText();
        String Marca = txtMarca.getText();
        String Color = txtColor.getText();
        String Tipo =  txtTipo.getText();
        String Valor = txtValor.getText();
      Object[] options = {"Tiene Multas", "No Tiene Multas"};
    int multasOption = JOptionPane.showOptionDialog(
            this,
            "¿El vehículo posee multas?",
            "Selección de Multas",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null,
            options,
            options[0]
    );

    boolean tieneMultas = multasOption == JOptionPane.YES_OPTION;
    double sueldoBasico = 435;
    double totalMatriculacion = 0;

    // Sumar multas al valor del vehículo
    if (tieneMultas) {
        totalMatriculacion += Double.parseDouble(Valor);
    }

    // Cobro por renovación de placas
    if (Cedula.startsWith("1") && Placa.startsWith("I")) {
        totalMatriculacion += 0.05 * sueldoBasico; // 5% del sueldo básico
    }

    // Multa por contaminación
    int añoFabricacion = Integer.parseInt(Fabricacion);
    int añosDeContaminacion = 2023 - añoFabricacion; // Asumiendo el año actual es 2023
    if (añoFabricacion < 2010) {
        totalMatriculacion += 0.02 * sueldoBasico * añosDeContaminacion; // 2% por cada año de contaminación
    }

    if ("Toyota".equalsIgnoreCase(Marca) && "Jeep".equalsIgnoreCase(Tipo)) {
        totalMatriculacion += 0.08 * Double.parseDouble(Valor); // 8% del valor del vehículo
    } else if ("Toyota".equalsIgnoreCase(Marca) && "Camioneta".equalsIgnoreCase(Tipo)) {
        totalMatriculacion += 0.12 * Double.parseDouble(Valor); // 12% del valor del vehículo
    } else if ("Suzuki".equalsIgnoreCase(Marca) && "Vitara".equalsIgnoreCase(Tipo)) {
        totalMatriculacion += 0.10 * Double.parseDouble(Valor); // 10% del valor del vehículo
    } else if ("Suzuki".equalsIgnoreCase(Marca) && "Automóvil".equalsIgnoreCase(Tipo)) {
        totalMatriculacion += 0.09 * Double.parseDouble(Valor); // 9% del valor del vehículo
    }

    JOptionPane.showMessageDialog(this, "El total a pagar por matriculación es: $" + totalMatriculacion, "Total de Matriculación", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_ButtnValidarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FichaAlexisEncalada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FichaAlexisEncalada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FichaAlexisEncalada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FichaAlexisEncalada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FichaAlexisEncalada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtnValidar;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JLabel lblAño;
    private javax.swing.JLabel lblCed;
    private javax.swing.JLabel lblCol;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblPla;
    private javax.swing.JLabel lblPro;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblVal;
    private javax.swing.JTextField txtAño;
    private javax.swing.JTextField txtCedu;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtTipo;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
